name: 🐞 Bug Report
description: Something is broken?
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        - Please do not report an issue for a version of ZipStream-PHP that is no longer
        - supported (< 2.0.0).
        - Please do not report an issue if you are using a version of PHP that is not
        - supported by the version of ZipStream-PHP you are using.
        - Please fill in this template according to your issue.
        - Please keep the table shown below at the top of your issue.
        - Please include the output of "composer info | sort".
        - Please post code as text (using proper markup). Do not post screenshots of
        - code.
        - Create a discussion instead if you are looking for support:
        - https://github.com/maennchen/ZipStream-PHP/discussions
        - Please remove this comment before submitting your issue.
  - type: input
    id: version
    attributes:
      label: ZipStream-PHP version
      placeholder: x.y.z
    validations:
      required: true
  - type: input
    id: php-version
    attributes:
      label: PHP version
      placeholder: x.y.z
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Provide a summary describing the problem you are experiencing.
    validations:
      required: true
  - type: textarea
    id: current-behaviour
    attributes:
      label: Current behavior
      description: What is the current (buggy) behavior?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      description: Provide steps to reproduce the bug.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behavior
      description: What was the expected (correct) behavior?
    validations:
      required: true
