on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"

name: "Beta Tag"

permissions:
  contents: read

jobs:
  release:
    name: "Release"

    permissions:
      contents: write

    uses: ./.github/workflows/part_release.yml
    with:
      releaseName: "${{ github.ref_name }}"

  docs:
    name: "Docs"

    needs: ["release"]

    uses: ./.github/workflows/part_docs.yml
    with:
      releaseName: "${{ github.ref_name }}"
